### PR TITLE
Update show.blade.php

### PR DESCRIPTION
**Pull request by acamilleri**
I add condition for propose to make team if user has no team

### CODE REVIEW

**Review by acamilleri — COMMENTED** [review]
Delete commit(acfc29d), i failed, line 35 not possible...

**Comment by chriskonnertz** [comment]
Why is it not possible? Maybe it is easier if you just commit the bugfix. Or is there no bugfix possible?

**Comment by krysennn** [comment]
Because line35 i use $team variable but it's not possible because i'm not in the foreach so $team doesn't exist

**Comment by chriskonnertz** [comment]
I've merged it and then manually removed the code that caused the bug.

**Pull request merged**
