### PR TITLE
sizeof() error when array is null, in PHP 7.2

### PR DESCRIPTION
**Pull request by onavascuez**
Fixed sizeof error.

### CODE REVIEW

**Comment by chriskonnertz** [comment]
Interesting change in PHP 7.2 (adding a warning), wasn't aware of that one.

**Comment by chriskonnertz** [comment]
However, it is fixed in `2.5-dev` though: https://github.com/Contentify/Contentify/blob/2.5-dev/contentify/ModelHandler.php#L233

But I guess it makes sense to also apply it to the `2.4`branch so I will merge your pull request.

Thank you for contributing!

**Comment by onavascuez** [comment]
Yes, also create_function() has been deprecated in PHP 7.2, and some class like:
Modules/Config/Http/Controllers/AdminConfigController.php:149 
Use this function. Is recommended tu use a clousure to solve this problem.

I make new PR when I arrive at home, and have time! ;)

**Comment by chriskonnertz** [comment]
ok great.

PS: I have also looked for more use of _sizeof()_ and made two more small changes, just to be sure. https://github.com/Contentify/Contentify/commit/c91296854dd934234d268c2e4b1a7e9832419be5

**Comment by chriskonnertz** [comment]
> Yes, also create_function() has been deprecated in PHP 7.2, and some class like:
Modules/Config/Http/Controllers/AdminConfigController.php:149

Yeah I believe this might work:

```
array_map(
                     function($i) {
                         return ".phpinfodisplay " . preg_replace( "/,/", ",.phpinfodisplay ", $i );
                     },
                     preg_split('/\n/', $matches[1]) // $matches[1] = style information
                     )
                 ).
```

**Comment by onavascuez** [comment]
I think so. It looks good!

**Pull request merged**
