### PR TITLE
Feature bracket

### PR DESCRIPTION
**Pull request by acamilleri**
For bracket it's only this commit: https://github.com/krysennn/Contentify/commit/7655af442eadf19ca985463cc1d437352b10e893

https://github.com/Contentify/Contentify/issues/105

### CODE REVIEW

**Comment by chriskonnertz** [comment]
Is this pull request ready to be merged?

(It has conflicts but I can resolve them, no problem.)

**Comment by acamilleri** [comment]
Hey :)

No it's not ready i found strange bug so i search but I have no time atm with my school and my work i will look this ASAP

**Comment by chriskonnertz** [comment]
No problem. I am busy as well so I know very well how difficult is to save time for coding. :)

**Comment by chriskonnertz** [comment]
Hello, I have changed the target branch of this pull request from "2.0-dev" to "2.0" sinde "2.0-dev" is no longer in use. Actually 2.0 is outdated as well, so the PR should target "2.2" but I do not know if chaning the target branch has any side effects on your work.

**Pull request closed without merging**
