### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by acamilleri**
Add french translation, it's not finish at the time ;)

### CODE REVIEW

**Comment by chriskonnertz** [comment]
Very cool! I do not speak French so I can't help here. :/

**Comment by krysennn** [comment]
It's not problem, i'm french but file validation.php is most difficult to translate in french because in english you can say: The email/ The username but in french it's: L'email or Le nom d'utilisateur so it's difficult but i will find it ^^

**Comment by chriskonnertz** [comment]
Well good news: The validation file is a part of Laravel. So it seems like other french Laravel users have faced this challenge as well. And look what I have found: https://github.com/caouecs/Laravel-lang/blob/master/src/fr/validation.php

**Comment by krysennn** [comment]
Oh yes !!! nice, I had not thought ^^ ;)

**Comment by krysennn** [comment]
I think it's finish now ;)

**Comment by chriskonnertz** [comment]
Ok I merged your changes. Also added "French" to the installer. 

It's pretty awesome to change the langauge to French and see how everything is being translated! :smile:

**Comment by chriskonnertz** [comment]
Can you do me a favor and translate these as well? They will be new in Contentify 2:
```
    'nothing_new'   => 'Sorry, nothing new. Please return later.',
    'back'          => 'Back',
    'theme'         => 'Theme',
    'loading'       => 'Loading',
    'lineup'        => 'Lineup',
```

If you translate them just post your translations here and I will add them in the code of Contentify 2.

**Comment by krysennn** [comment]
Yes no problem ;)

```
'nothing_new'   => 'Désoler, rien de nouveau. Revenez plus tard',
'back'          => 'Retour',
'theme'         => 'Thème',
'loading'       => 'Chargement',
'lineup'        => 'Lineup OR Composition OR Composition de l\'équipe', you can use "Lineup" because french people saying Lineup when he playing League of legend, counter strike ... or you can use "composition/composition de l'équipe" because in french there are no word for linup, it's "composition de l'équipe".
```

You can request other things about contentify, it's not problem, i would help you :smiley: 
I answered on bitbucket :smile:

**Comment by chriskonnertz** [comment]
Thanks! Added these lines. Thank you as well for your help with the translations! It adds a lot of value to the CMS.

**Pull request merged**
