### PR TITLE
 Fix create_function() with clousure to prepare for PHP7.2. Updated gitignore

### PR DESCRIPTION
**Pull request by onavascuez**
- Fix create_function() with clousure to prepare for PHP7.2.
- Added database.ini to gitignote.

### CODE REVIEW

**Review by chriskonnertz — APPROVED** [review]

**Comment by chriskonnertz** [comment]
Thank you for creating this pull request! I' ve merged it.

**Comment by onavascuez** [comment]
Thanks to you for develop this project! ;)
I continue using 2.4, and resolving all bugs I found.

**Comment by chriskonnertz** [comment]
Great! Even though I hope you will not find any new bugs ;) ;)

**Comment by onavascuez** [comment]
I have one from:
https://github.com/Contentify/Contentify/blob/1f224e920714805c270f076b530b439bcc4259b1/app/Modules/Forums/ForumReportCase.php

And reported in this issue:
https://github.com/Contentify/Contentify/issues/418#issue-354011210

**Comment by chriskonnertz** [comment]
Workaround:

https://github.com/Contentify/Contentify/blob/v2.4/config/database.php#L50
Set strict to false

**Pull request merged**
