### PR TITLE
Psr2 code fixup

### PR DESCRIPTION
**Pull request by funtimeerror**
Checklist:

✓ I (at least tried to) stick to the PSR code style guide
✓ I have chosen the current development branch as the target
✓ I will add a link to the related issue (if there is one)

1) Massive PSR2 code fixup (thank you phpcbf!!!! )
`./vendor/squizlabs/php_codesniffer/bin/phpcbf --ignore=/vendor/*,/app/Modules/*/Resources/Views/*.php,_ide_helper.php --standard=PSR2 --exclude=PSR2.Files.EndFileNewline,Squiz.Functions.MultiLineFunctionDeclaration,Squiz.WhiteSpace.SuperfluousWhitespace,Squiz.Functions.FunctionDeclaration,PSR2.Methods.FunctionClosingBrace -n --encoding=utf-8 --extensions=php ./*`
2) updated travis.yml to exclude front-end views from being scanned

only 3 issue types remain
### Each class must be in a namespace of at least one level (a top-level vendor name)
* AppBridge.php
* database/migrations/*.php
* database/seeds/DatabaseSeeder.php
* public/update.php
* public/install.php

### Method name is not in camel caps format
* app/Modules/Cups/Match.php ("Match::left_participant" and "Match::right_participant")

### There must be a comment when fall-through is intentional in a non-empty case body
* Hover.php - around line 144, missing a break statement before the default case?

after the above exeptions are fixed, the travis-ci job should run without errors 😃

### CODE REVIEW

**Comment by chriskonnertz** [comment]
> Each class must be in a namespace of at least one level (a top-level vendor name)

`AppBridge.php`, `install.php` and `update.php` are not part of the regular section of the application. These are special files. We could give them a namespace but just for the sake of passing a check? Hm...

I am suprised that `server.php` is not mentioned, it does not have a namespace as well... 

The files in the `database`folder follow a scheme defined by Laravel and they are ought to have no namespace. That's Laravel logic and we do not want to touch it.

> Method name is not in camel caps format

Yeah might be worth to check this. Maybe it did not work to use camel case there in the past but works now with Laravel 5.5... Or maybe it's just a mistake.

> There must be a comment when fall-through is intentional in a non-empty case body

True, this did not had any effect but yeah, the `break`was missing. Added it here: https://github.com/Contentify/Contentify/commit/464eb850146f94251f995100b2c2019e92500849

**Comment by chriskonnertz** [comment]
Do you know if there is a way to make it ignore inline `<?php` tags (in Blade templates)?

Because it does not really understand them and destroys the formatting inside these tags... One example: https://github.com/Contentify/Contentify/pull/531/files#diff-16edb251e1029f058ea4216241208cc0

**Comment by chriskonnertz** [comment]
So I have merged it but I will now revert some of the changes manually. :stuck_out_tongue:

**Comment by chriskonnertz** [comment]
=> https://github.com/Contentify/Contentify/pull/533

**Comment by chriskonnertz** [comment]
Merged into the `3.0-dev` branch. Thank you for your contribution. This helped to improve code quality! :)

**Comment by funtimeerror** [comment]
Going forward, phpcs won’t scan the blade templates, that was fixed in the .travis.yml update of this pr

As for the namespace ones, I think there is a way to bypass those alerts, I’ll look this afternoon.

**Pull request merged**
