### PR TITLE
New translation: Portuguese + added missing translation in spanish 

### PR DESCRIPTION
**Pull request by Franpepper**
Im working on the Portuguese translation, maybe by next Saturday it is 100% complete including all modules.

Spanish: add translation to line 58 on `app.php` 

Checklist:

✓ I (at least tried to) stick to the PSR code style guide
✓ I have chosen the current development branch as the target
✓ I will add a link to the related issue (if there is one)

### CODE REVIEW

**Comment by chriskonnertz** [comment]
Hello @Franpepper ,

wow, great! Definetely looking forward to the complete translation. Would be so great if you complete it. I would merge it then so it's in 3.0 (great that you work with 3.0!), and from then on officially support it. :+1:

**Review by chriskonnertz — COMMENTED** [review]
Cannot do a real review now, but loooks good at the first glance! I will merge it once it is complete.

**Comment by Franpepper** [comment]
I think the translation is finished, let me know if I'm forgetting to translate something else.
I was also making some corrections to the Spanish translation.

**Comment by chriskonnertz** [comment]
Hi, awesome, I hope I will be able to review it at the weekend (tomorrow).

**Review by chriskonnertz — APPROVED** [review]

**Comment by chriskonnertz** [comment]
Finally merged, thanks again!

**Pull request merged**
