### PR TITLE
game icon size, awarded team

### PR DESCRIPTION
**Pull request by torriz**
Set game size to 16x16. 
In case the uploaded game "icon" is bigger and perhaps used as a bigger version other places

Added the team that got the award to the table.

### CODE REVIEW

**Comment by chriskonnertz** [comment]
Hi,

I think this will not always work: `$award->team->title` since an award do not have to be tied to a team. Please check this (create a new award and try not to assign it to a team, save it, go to the awards overview page). 

I believe that if we want to add it (I am not sure yet) we would have to do something like: `$award->team ? $award->team->title : ''`

**Comment by chriskonnertz** [comment]
However, fixing the size of the icon is a good idea, we should do that.

**Comment by torriz** [comment]
> Hi,
> 
> I think this will not always work: `$award->team->title` since an award do not have to be tied to a team. Please check this (create a new award and try not to assign it to a team, save it, go to the awards overview page).
> 
> I believe that if we want top add it (I am not sure yet) we would have to do something like: `$award->team ? $award->team->title : ''`

Oh, you're probably right.. I'll check 👍

**Comment by torriz** [comment]
Yup.. Should be good now

**Comment by chriskonnertz** [comment]
Thanks! I will test this to see if it works and if it is a useful enhancement.

**Comment by chriskonnertz** [comment]
Merged. I have done these changes afterwards:
- Put the team column after the title column since I consider it less important
- Link the team (as you had suggested in the other PR)
- Also added the column on the admin page

Thank you for your contribution!

**Pull request merged**
