### PR TITLE
Spanish language for Contentify 2.5

### PR DESCRIPTION
**Pull request by onavascuez**
If I do not leave anything, and I have not messed with the merge, this is it! :)
I've tried the web and it seems to be all good.
Check it if you can!

### CODE REVIEW

**Comment by chriskonnertz** [comment]
I’ll check it out! T y.

**Review by chriskonnertz — APPROVED** [review]

**Comment by chriskonnertz** [comment]
Merged! Thank you so much! This is really a great improvement for everyone who wants to have their website in Spanish. Great job.

**Comment by onavascuez** [comment]
You're welcome! It is a pleasure to collaborate on projects like this one! :)

**Comment by chriskonnertz** [comment]
Great attitude!

**Pull request merged**
