### PR TITLE
Add christmas snow for Contentify Themes.

### PR DESCRIPTION
**Pull request by acamilleri**
Settings are in Admin Backend (activate or not and change color of snow).
Add new field in InstallController

### CODE REVIEW

**Comment by krysennn** [comment]
I edit z-index:3; to z-index:0; to fix bug with link in the page.

**Comment by chriskonnertz** [comment]
Cool! I will review this pull request at the weekend. :)

**Comment by krysennn** [comment]
Yes but wait the next commit i will trying to push it before sunday, i will work on z-index in Phobos and Morpheus Theme because snow is behind all block like slider ...
https://github.com/Contentify/Contentify/issues/104#issuecomment-263238733

**Comment by chriskonnertz** [comment]
Ok :)

**Comment by krysennn** [comment]
I think is it ok for MorpheusTheme and PhobosTheme, sorry for the late 👎

**Comment by chriskonnertz** [comment]
Nice! The diff ( https://github.com/Contentify/Contentify/pull/107/files ) shows a  lot of differences that do not really seem to have something to do with the snow-stuff. Especially take a look at these lines: https://github.com/Contentify/Contentify/pull/107/commits/c6ab74feb0ee52d44e352942bfd32b219f42735e#diff-cadfad46ae75a497210cea027433b57fL571

Did you commit code from other features?

**Comment by krysennn** [comment]
Oh yes, because i work on Snow feature and on the Bracket feature and i failed because i dont create branch for snow and i commit all in 2.0-dev in my fork ...

c6ab74f#diff-cadfad46ae75a497210cea027433b57fL571 -> it's for bracket feature.

I finish first part of bracket here:
https://github.com/Contentify/Contentify/pull/115

So i make branch with name "bracket" and i commit my files of bracket in bracket branch but when i pull request i see files for Snow and Bracket 👎 
So i will waiting your merge of snow feature and i will make new pull requests for bracket.

I will read again Git documentation ^^

**Comment by chriskonnertz** [comment]
Hey I finally migrated from my old pc to my new pc. So I have started to work on Contentify again. I hope I will be able to review you pull requests soon. Finally. :D

**Comment by acamilleri** [comment]
@chriskonnertz yeah :D

**Comment by chriskonnertz** [comment]
Finally merged it. Sorry for the delay. I was very busy and this was a very big pull request. :p

**Pull request merged**
